title: Bergerb
subtitle: Adventures in Software Development and Life
author: Brent Berger
avatar_url: https://2.gravatar.com/avatar/b9a21f340f4d0b1a72356d69fda65571?s=160  # Should be 160x160px.
# email: your-email@domain.com  # Comment out this line if you don't want to expose your email.
description: > # this means to ignore newlines until "twitter_username:"
  Technology, Software Development, and Life.
repository: bergerb/bergerb.github.io

navbar-links:
  About Me: "about"
  Explore: "explore"

# Google Analytics
google_analytics: UA-42285689-1
round-avatar: true

# contact
contact:
#  email: your-email@domain.com  # Comment out this line if you don't want to expose your email.
#  url: https://your-contact-url # Uncomment this to provide a contact form url instead of an email

# social links
#twitter_username: bergerb
mastodon:
  username: bergerb
  instance: hachyderm.io
github_username:  bergerb
rss: rss
#dribbble_username: jekyll
#facebook_username: jekyll
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

# 
# Subscribe Feed
# 
# By default, your site generates a subscription feed (RSS/Atom) at /feed.xml
# Uncomment the next two lines to change the path.
# feed:
#   path: /atom.xml

# If you use a feed publisher such as Feedburner, uncomment the next line
# subscribe_rss: https://your-feedburner-url/

# Homepage
show_excerpts: true  # set to true to show excerpts on the homepage, otherwise full posts are shown

# Comments
# To enable comments, set the `enabled` field to true and supply either a Disqus short name or a Jekyll comments receiver
comments:
  enabled: true
  show_count: true
#  receiver: https://.../  # See https://haacked.com/archive/2018/06/24/comments-for-jekyll-blogs/ for more information.
disqus_shortname: bergerb

emptyArray: [] # Leave this here.

# haackbar date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
haackbar:
  date_format: "%b %-d, %Y"

#
# Jekyll Settings
#
permalink: /archive/:year/:month/:day/:title/
paginate: 5 # number of posts per page
page_group_size: 5 # number of pages to group by in the pagination.
paginate_path: "/archive/page/:num"

# Front matter defaults
defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: post
      comments: true
  -
    scope:
      path: "pages"
      type: "pages"
    values:
      layout: page
      comments: false
  -
    scope:
      path: "assets/pages"
      type: "pages"
    values:
      layout: page
      comments: false

# Build settings
markdown: kramdown
kramdown:
  hard_wrap: false
remote_theme: bergerb/haackbar

exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache